import { MARKET_SELECT_OPTIONS } from '@/lib/samba/markets'

// 마켓 셀렉트 옵션 (markets.ts 단일 소스)
export const MARKET_TYPES = MARKET_SELECT_OPTIONS

// Claude AI 모델 목록
export const CLAUDE_MODELS = [
  { value: 'claude-sonnet-4-6', label: 'Claude Sonnet 4.6 (권장)' },
  { value: 'claude-opus-4-6', label: 'Claude Opus 4.6 (고성능)' },
  { value: 'claude-haiku-4-5-20251001', label: 'Claude Haiku 4.5 (빠름/저렴)' },
]

// AI 기능 목록
export const AI_FEATURES = [
  { key: 'productName', label: '상품명 가공' },
  { key: 'description', label: '상세설명 생성' },
  { key: 'csReply', label: 'CS 자동 답변' },
  { key: 'autoTag', label: '태그 자동 생성' },
  { key: 'imageProcess', label: '이미지 가공' },
]

// 환율 통화 코드 타입
export type ExchangeCurrencyCode = 'USD' | 'JPY' | 'CNY' | 'EUR'

// 환율 항목 타입
export type ExchangeRateItem = {
  code: ExchangeCurrencyCode
  label: string
  baseRate: number
  adjustment: number
  fixedRate: number
  effectiveRate: number
  useFixed: boolean
}

// 환율 응답 타입
export type ExchangeRateResponse = {
  provider: string
  base: string
  fetchedAt?: string
  publishedAt?: string
  currencies: Record<ExchangeCurrencyCode, ExchangeRateItem>
}

// 환율 통화 표시 순서
export const EXCHANGE_CURRENCY_ORDER: ExchangeCurrencyCode[] = ['USD', 'JPY', 'CNY', 'EUR']

// 통화별 표시 단위 배율 (JPY는 100엔 기준)
export const getExchangeDisplayMultiplier = (code: ExchangeCurrencyCode) => code === 'JPY' ? 100 : 1

// 환율 초기값
export const EMPTY_EXCHANGE_RATES: ExchangeRateResponse = {
  provider: '',
  base: 'KRW',
  currencies: {
    USD: { code: 'USD', label: '달러', baseRate: 0, adjustment: 0, fixedRate: 0, effectiveRate: 0, useFixed: false },
    JPY: { code: 'JPY', label: '엔화', baseRate: 0, adjustment: 0, fixedRate: 0, effectiveRate: 0, useFixed: false },
    CNY: { code: 'CNY', label: '위안화', baseRate: 0, adjustment: 0, fixedRate: 0, effectiveRate: 0, useFixed: false },
    EUR: { code: 'EUR', label: '유로화', baseRate: 0, adjustment: 0, fixedRate: 0, effectiveRate: 0, useFixed: false },
  },
}

// 마켓별 스토어 연결 필드 정의 타입
export interface MarketConfig {
  key: string
  label: string
  authField?: string
  guideUrl?: string // API 가이드 링크
  fields: { name: string; label: string; type: string; placeholder?: string; options?: { value: string; label: string }[]; disabled?: boolean; fixedValue?: number; description?: string }[]
}

// 마켓별 스토어 연결 설정
export const STORE_MARKETS: MarketConfig[] = [
  { key: 'smartstore', label: '스마트스토어', authField: 'clientSecret', guideUrl: 'https://apicenter.commerce.naver.com/ko/member/home', fields: [
    { name: 'businessName', label: '사업자명', type: 'text', placeholder: '상호명 입력' },
    { name: 'storeId', label: '스토어 ID', type: 'text' },
    { name: 'clientId', label: 'Client ID', type: 'text' },
    { name: 'clientSecret', label: 'Client Secret', type: 'password' },
    { name: 'asPhone', label: 'A/S 전화번호', type: 'text', placeholder: '010-1234-5678' },
    { name: 'asMessage', label: 'A/S 안내 문구', type: 'text', placeholder: '상세페이지 참조' },
    { name: 'discountRate', label: '즉시할인율(%)', type: 'number', disabled: true, fixedValue: 25, description: 'SmartStore 판매가 10원 단위 제약으로 25% 고정' },
    { name: 'returnFee', label: '반품배송비(편도)', type: 'number', placeholder: '3000' },
    { name: 'exchangeFee', label: '교환배송비(왕복)', type: 'number', placeholder: '6000' },
    { name: 'jejuFee', label: '제주/도서산간 추가비', type: 'number', placeholder: '3000' },
    { name: 'returnSafeguard', label: '반품안심케어', type: 'select', options: [
      { value: '', label: '설정안함' },
      { value: 'true', label: '설정함' },
    ]},
    { name: 'stockQuantity', label: '재고수량', type: 'number', placeholder: '999 (기본값)' },
    { name: 'naverShopping', label: '가격비교 사이트 등록', type: 'checkbox', placeholder: '네이버쇼핑에 상품 노출' },
    { name: 'maxCount', label: '최대 등록 갯수', type: 'number', placeholder: '∞ 무제한' },
    { name: '_divider_purchase', label: '구매/리뷰 혜택 조건', type: 'divider' },
    { name: 'multiPurchaseDiscount', label: '복수구매할인', type: 'select', options: [
      { value: '', label: '설정안함' },
      { value: 'true', label: '설정함' },
    ]},
    { name: 'multiPurchaseQty', label: '복수구매 수량 (N개 이상)', type: 'number', placeholder: '2' },
    { name: 'multiPurchaseRate', label: '복수구매 할인율 (%)', type: 'number', placeholder: '1' },
    { name: '_divider_point', label: '포인트', type: 'divider' },
    { name: 'purchasePointEnabled', label: '상품 구매 시 지급', type: 'checkbox' },
    { name: 'purchasePointRate', label: '구매 적립률 (%)', type: 'number', placeholder: '1' },
    { name: '_divider_review', label: '상품리뷰 작성시 지급', type: 'divider' },
    { name: 'reviewPointEnabled', label: '리뷰 포인트 지급', type: 'checkbox' },
    { name: 'reviewTextPoint', label: '텍스트 리뷰 작성', type: 'number', placeholder: '원' },
    { name: 'reviewPhotoPoint', label: '포토/동영상 리뷰 작성', type: 'number', placeholder: '원' },
    { name: 'reviewMonthTextPoint', label: '한달사용 텍스트 리뷰', type: 'number', placeholder: '원' },
    { name: 'reviewMonthPhotoPoint', label: '한달사용 포토/동영상 리뷰', type: 'number', placeholder: '원' },
    { name: '_info_storeMember', label: '알림받기 동의고객 포인트는 셀러센터에서 직접 설정', type: 'info' },
  ]},
  { key: 'gmarket', label: '지마켓', authField: 'storeId', fields: [
    { name: 'businessName', label: '사업자명', type: 'text', placeholder: '상호명 입력' },
    { name: 'storeId', label: '판매자 ID', type: 'text', placeholder: 'ESMPlus 판매자 ID' },
    { name: '_divider_shipping', label: '배송정책 (ESMPlus에서 불러오기)', type: 'divider' },
    { name: 'shippingFeeType', label: '배송비 설정', type: 'select', options: [
      { value: 'FREE', label: '무료' }, { value: 'PAID', label: '유료' },
    ]},
    { name: 'shippingPlaceNo', label: '출고지', type: 'esm-place-select' },
    { name: 'returnPlaceNo', label: '반품/교환지', type: 'esm-place-select' },
    { name: 'dispatchPolicyNo', label: '배송 정책', type: 'esm-dispatch-select' },
    { name: 'shippingCompanyNo', label: '발송 택배사', type: 'select', options: [
      { value: '', label: '설정안함' },
      { value: '1', label: 'CJ대한통운' },
      { value: '5', label: '롯데택배' },
      { value: '6', label: '로젠택배' },
      { value: '7', label: '한진택배' },
      { value: '9', label: '우체국' },
    ]},
    { name: 'shippingFee', label: '배송비', type: 'number', placeholder: '0' },
    { name: 'jejuFee', label: '제주 및 부속도서 추가비', type: 'number', placeholder: '5000' },
    { name: 'islandFee', label: '도서지방 및 산간 추가비', type: 'number', placeholder: '5000' },
    { name: 'returnFee', label: '반품 배송비(편도)', type: 'number', placeholder: '3000' },
    { name: '_info_returnfee_warning', label: '※업로드된 상품은 배송정책이 변경되더라도 적용되지 않으니 스토어에서 직접 변경해주세요.', type: 'info' },
    { name: '_divider_other', label: '기타정보', type: 'divider' },
    { name: 'asPhone', label: 'A/S 전화번호', type: 'text', placeholder: '010-1234-5678' },
    { name: 'asMessage', label: 'A/S 안내 문구', type: 'text', placeholder: '상세페이지 참조' },
    { name: 'stockQuantity', label: '재고수량', type: 'number', placeholder: '999 (기본값)' },
    { name: 'maxCount', label: '최대 등록 갯수', type: 'number', placeholder: '∞ 무제한' },
    { name: '_divider_discount', label: '포인트/할인설정', type: 'divider' },
    { name: 'discountRate', label: '즉시할인율(%)', type: 'number', placeholder: '0 (미설정)' },
    { name: '_divider_purchase', label: '복수구매 할인', type: 'divider' },
    { name: 'multiPurchaseDiscount', label: '복수구매할인', type: 'select', options: [
      { value: '', label: '설정안함' }, { value: 'true', label: '설정함' },
    ]},
    { name: 'multiPurchaseQty', label: '복수구매 수량 (N개 이상)', type: 'number', placeholder: '2' },
    { name: 'multiPurchaseRate', label: '복수구매 할인율 (%)', type: 'number', placeholder: '1' },
    { name: '_divider_point', label: '포인트', type: 'divider' },
    { name: 'purchasePointEnabled', label: '상품 구매 시 지급', type: 'checkbox' },
    { name: 'purchasePointRate', label: '구매 적립률 (%)', type: 'number', placeholder: '1' },
    { name: '_divider_review', label: '상품리뷰 작성시 지급', type: 'divider' },
    { name: 'reviewPointEnabled', label: '리뷰 포인트 지급', type: 'checkbox' },
    { name: 'reviewTextPoint', label: '텍스트 리뷰 작성', type: 'number', placeholder: '원' },
    { name: 'reviewPhotoPoint', label: '포토/동영상 리뷰 작성', type: 'number', placeholder: '원' },
    { name: 'reviewMonthTextPoint', label: '한달사용 텍스트 리뷰', type: 'number', placeholder: '원' },
    { name: 'reviewMonthPhotoPoint', label: '한달사용 포토/동영상 리뷰', type: 'number', placeholder: '원' },
  ]},
  { key: 'auction', label: '옥션', authField: 'storeId', fields: [
    { name: 'businessName', label: '사업자명', type: 'text', placeholder: '상호명 입력' },
    { name: 'storeId', label: '판매자 ID', type: 'text', placeholder: 'ESMPlus 판매자 ID' },
    { name: '_divider_shipping', label: '배송정책 (ESMPlus에서 불러오기)', type: 'divider' },
    { name: 'shippingFeeType', label: '배송비 설정', type: 'select', options: [
      { value: 'FREE', label: '무료' }, { value: 'PAID', label: '유료' },
    ]},
    { name: 'shippingPlaceNo', label: '출고지', type: 'esm-place-select' },
    { name: 'returnPlaceNo', label: '반품/교환지', type: 'esm-place-select' },
    { name: 'dispatchPolicyNo', label: '배송 정책', type: 'esm-dispatch-select' },
    { name: 'shippingCompanyNo', label: '발송 택배사', type: 'select', options: [
      { value: '', label: '설정안함' },
      { value: '1', label: 'CJ대한통운' },
      { value: '5', label: '롯데택배' },
      { value: '6', label: '로젠택배' },
      { value: '7', label: '한진택배' },
      { value: '9', label: '우체국' },
    ]},
    { name: 'shippingFee', label: '배송비', type: 'number', placeholder: '0' },
    { name: 'jejuFee', label: '제주 및 부속도서 추가비', type: 'number', placeholder: '5000' },
    { name: 'islandFee', label: '도서지방 및 산간 추가비', type: 'number', placeholder: '5000' },
    { name: 'returnFee', label: '반품 배송비(편도)', type: 'number', placeholder: '3000' },
    { name: '_info_returnfee_warning', label: '※업로드된 상품은 배송정책이 변경되더라도 적용되지 않으니 스토어에서 직접 변경해주세요.', type: 'info' },
    { name: '_divider_other', label: '기타정보', type: 'divider' },
    { name: 'asPhone', label: 'A/S 전화번호', type: 'text', placeholder: '010-1234-5678' },
    { name: 'asMessage', label: 'A/S 안내 문구', type: 'text', placeholder: '상세페이지 참조' },
    { name: 'stockQuantity', label: '재고수량', type: 'number', placeholder: '999 (기본값)' },
    { name: 'maxCount', label: '최대 등록 갯수', type: 'number', placeholder: '∞ 무제한' },
    { name: '_divider_discount', label: '포인트/할인설정', type: 'divider' },
    { name: 'discountRate', label: '즉시할인율(%)', type: 'number', placeholder: '0 (미설정)' },
    { name: '_divider_purchase', label: '복수구매 할인', type: 'divider' },
    { name: 'multiPurchaseDiscount', label: '복수구매할인', type: 'select', options: [
      { value: '', label: '설정안함' }, { value: 'true', label: '설정함' },
    ]},
    { name: 'multiPurchaseQty', label: '복수구매 수량 (N개 이상)', type: 'number', placeholder: '2' },
    { name: 'multiPurchaseRate', label: '복수구매 할인율 (%)', type: 'number', placeholder: '1' },
    { name: '_divider_point', label: '포인트', type: 'divider' },
    { name: 'purchasePointEnabled', label: '상품 구매 시 지급', type: 'checkbox' },
    { name: 'purchasePointRate', label: '구매 적립률 (%)', type: 'number', placeholder: '1' },
    { name: '_divider_review', label: '상품리뷰 작성시 지급', type: 'divider' },
    { name: 'reviewPointEnabled', label: '리뷰 포인트 지급', type: 'checkbox' },
    { name: 'reviewTextPoint', label: '텍스트 리뷰 작성', type: 'number', placeholder: '원' },
    { name: 'reviewPhotoPoint', label: '포토/동영상 리뷰 작성', type: 'number', placeholder: '원' },
    { name: 'reviewMonthTextPoint', label: '한달사용 텍스트 리뷰', type: 'number', placeholder: '원' },
    { name: 'reviewMonthPhotoPoint', label: '한달사용 포토/동영상 리뷰', type: 'number', placeholder: '원' },
  ]},
  { key: 'coupang', label: '쿠팡', authField: 'secretKey', guideUrl: 'https://wing.coupang.com/vendor/openapi/application', fields: [
    { name: 'businessName', label: '사업자명', type: 'text', placeholder: '상호명 입력' },
    { name: 'storeId', label: '스토어 ID', type: 'text' },
    { name: 'vendorId', label: 'Vendor 업체코드', type: 'text', placeholder: 'Wing 판매자 업체코드' },
    { name: 'accessKey', label: 'Access key', type: 'text' },
    { name: 'secretKey', label: 'Secret key', type: 'password' },
    { name: 'asPhone', label: 'A/S 전화번호', type: 'text', placeholder: '0507-1234-5678' },
    { name: 'asMessage', label: 'A/S 안내 문구', type: 'text', placeholder: '상세페이지 참조' },
    { name: 'discountRate', label: '즉시할인율(%)', type: 'number', placeholder: '0 (미설정)' },
    { name: 'returnFee', label: '반품배송비(편도)', type: 'number', placeholder: '3000' },
    { name: 'exchangeFee', label: '교환배송비(왕복)', type: 'number', placeholder: '6000' },
    { name: 'jejuFee', label: '제주/도서산간 추가비', type: 'number', placeholder: '3000' },
    { name: 'stockQuantity', label: '재고수량', type: 'number', placeholder: '999 (기본값)' },
    { name: '_divider_shipping_coupang', label: '출고지/반품지 (Wing API 조회)', type: 'divider' },
    { name: 'outboundShippingPlaceCode', label: '출고지', type: 'coupang-outbound', placeholder: '버튼으로 불러오기' },
    { name: 'returnCenterCode', label: '반품지', type: 'coupang-return', placeholder: '버튼으로 불러오기' },
    { name: 'maxCount', label: '최대 등록 갯수', type: 'number', placeholder: '∞ 무제한' },
  ]},
  { key: 'lotteon', label: '롯데ON', authField: 'apiKey', guideUrl: 'https://openapi.lotteon.com', fields: [
    { name: 'businessName', label: '사업자명', type: 'text', placeholder: '상호명 입력' },
    { name: 'storeId', label: '스토어 ID', type: 'text' },
    { name: 'apiKey', label: '롯데ON API key', type: 'text' },
    { name: '_divider_shipping_infra', label: '배송 인프라', type: 'divider' },
    { name: 'dvCstPolNo', label: '배송정책번호', type: 'lotteon-policy-select' },
    { name: 'dvIslandCstPolNo', label: '도서산간 배송정책번호', type: 'lotteon-policy-select' },
    { name: 'owhpNo', label: '출고지번호', type: 'lotteon-departure-select' },
    { name: 'rtrpNo', label: '회수지번호', type: 'lotteon-return-select' },
    { name: 'bundleDelivery', label: '묶음배송', type: 'select', options: [
      { value: 'N', label: '불가능' }, { value: 'Y', label: '가능' },
    ]},
    { name: 'dispatchDays', label: '발송완료 N일 이내', type: 'select', options: [
      { value: '1', label: '1일' }, { value: '2', label: '2일' }, { value: '3', label: '3일' },
    ]},
    { name: 'asPhone', label: 'A/S 전화번호', type: 'text', placeholder: '010-1234-5678' },
    { name: 'promotionMessage', label: '상품홍보문구', type: 'text', placeholder: '홍보 문구 입력' },
    { name: 'returnFee', label: '반품배송비(편도)', type: 'number', placeholder: '3000' },
    { name: 'exchangeFee', label: '교환배송비(왕복)', type: 'number', placeholder: '6000' },
    { name: 'jejuFee', label: '제주/도서산간 추가비', type: 'number', placeholder: '3000' },
    { name: 'stockQuantity', label: '재고수량', type: 'number', placeholder: '999 (기본값)' },
    { name: 'maxCount', label: '최대 등록 갯수', type: 'number', placeholder: '∞ 무제한' },
    { name: '_divider_review', label: 'LPOINT 추가적립', type: 'divider' },
    { name: 'reviewTextPoint', label: '구매확정 적립 LPOINT', type: 'number', placeholder: '원' },
    { name: 'reviewPhotoPoint', label: '리뷰작성시 LPOINT', type: 'number', placeholder: '원' },
    { name: 'reviewMonthTextPoint', label: '사진첨부시 LPOINT', type: 'number', placeholder: '원' },
    { name: 'reviewMonthPhotoPoint', label: '동영상첨부시 LPOINT', type: 'number', placeholder: '원' },
    { name: '_divider_event_exclude', label: '행사 제외 설정', type: 'divider' },
    { name: 'ownerDiscountExclude', label: '오너스할인', type: 'radio', options: [
      { value: 'N', label: '제외안함' }, { value: 'Y', label: '제외' },
    ]},
    { name: 'unitCouponExclude', label: '상품단위쿠폰', type: 'radio', options: [
      { value: 'N', label: '제외안함' }, { value: 'Y', label: '제외' },
    ]},
    { name: 'deliveryCouponExclude', label: '배송쿠폰', type: 'radio', options: [
      { value: 'N', label: '제외안함' }, { value: 'Y', label: '제외' },
    ]},
    { name: 'cmPcsExclude', label: '가격비교채널할인(CM+PCS)', type: 'radio', options: [
      { value: 'N', label: '제외안함' }, { value: 'Y', label: '제외' },
    ]},
    { name: 'pcsExclude', label: '가격비교(PCS)할인', type: 'radio', options: [
      { value: 'N', label: '제외안함' }, { value: 'Y', label: '제외' },
    ]},
  ]},
  { key: '11st', label: '11번가', authField: 'apiKey', guideUrl: 'https://openapi.11st.co.kr/openapi/OpenApiServiceRegister.tmall', fields: [
    { name: 'businessName', label: '사업자명', type: 'text', placeholder: '상호명 입력' },
    { name: 'storeId', label: '상품전송 ID', type: 'text', placeholder: '11번가 셀러 ID' },
    { name: 'apiKey', label: 'Open API Key', type: 'text', placeholder: '32자리 Open API Key' },
    { name: 'sellerType', label: '판매자 형태', type: 'select', options: [
      { value: 'domestic', label: '국내판매자(국내사업자)' },
      { value: 'global', label: '글로벌판매자(국내사업자)' },
      { value: 'overseas', label: '국내판매자(해외사업자)' },
    ]},
    { name: 'taxType', label: '과세구분', type: 'select', options: [
      { value: '01', label: '과세' }, { value: '02', label: '면세' },
    ]},
    { name: 'deliveryType', label: '배송비 유형', type: 'select', options: [
      { value: 'DV_FREE', label: '무료배송' }, { value: 'DV_FIX', label: '유료배송(고정)' }, { value: 'DV_COND', label: '조건부 무료' },
    ]},
    { name: 'deliveryFee', label: '배송비', type: 'number', placeholder: '0' },
    { name: 'asPhone', label: 'A/S 전화번호', type: 'text', placeholder: '010-1234-5678' },
    { name: 'asMessage', label: 'A/S안내', type: 'text', placeholder: '상세페이지 참조' },
    { name: 'promotionMessage', label: '상품홍보문구', type: 'text', placeholder: '홍보 문구 입력 (한글 최대 14자)' },
    { name: 'discountRate', label: '즉시할인율(%)', type: 'number', placeholder: '0 (미설정)' },
    { name: 'returnFee', label: '반품배송비(편도)', type: 'number', placeholder: '4000' },
    { name: 'exchangeFee', label: '교환배송비(왕복)', type: 'number', placeholder: '8000' },
    { name: 'jejuFee', label: '제주 추가배송비', type: 'number', placeholder: '4000' },
    { name: 'islandFee', label: '도서지역 추가배송비', type: 'number', placeholder: '5000' },
    { name: 'shipFromAddress', label: '출고지 주소', type: 'text', placeholder: '출고지 주소 입력' },
    { name: 'returnAddress', label: '반품지 주소', type: 'text', placeholder: '반품지 주소 입력' },
    { name: 'dispatchTemplateNo', label: '발송정책', type: 'elevenst-dispatch-select' },
    { name: 'origin', label: '원산지', type: 'text', placeholder: '기타' },
    { name: 'returnExchangeGuide', label: '반품/교환 안내', type: 'text', placeholder: '상세페이지 참조' },
    { name: 'minorRestrict', label: '청소년구매불가', type: 'select', options: [
      { value: 'N', label: '아니오' }, { value: 'Y', label: '예' },
    ]},
    { name: 'stockQuantity', label: '재고수량', type: 'number', placeholder: '999 (기본값)' },
    { name: 'maxCount', label: '최대 등록 갯수', type: 'number', placeholder: '∞ 무제한' },
    { name: '_divider_purchase', label: '복수구매 할인', type: 'divider' },
    { name: 'multiPurchaseDiscount', label: '복수구매 할인', type: 'select', options: [
      { value: '', label: '설정안함' }, { value: 'true', label: '설정함' },
    ]},
    { name: 'multiPurchaseBasisType', label: '기준', type: 'select', options: [
      { value: '01', label: '수량기준' }, { value: '02', label: '금액기준' },
    ]},
    { name: 'multiPurchaseDiscountMethod', label: '할인', type: 'select', options: [
      { value: '02', label: '원 할인' }, { value: '01', label: '% 할인' },
    ]},
    { name: 'multiPurchaseQty', label: 'N개 이상 구매시', type: 'number', placeholder: '2' },
    { name: 'multiPurchaseAmt', label: '개당 할인값 (원 또는 %)', type: 'number', placeholder: '1000' },
    { name: 'multiPurchasePeriodEnabled', label: '할인 적용기간 설정', type: 'checkbox' },
    { name: 'multiPurchaseStartDate', label: '할인 시작일 (YYYYMMDD)', type: 'text', placeholder: '20260101' },
    { name: 'multiPurchaseEndDate', label: '할인 종료일 (YYYYMMDD)', type: 'text', placeholder: '20261231' },
    { name: '_divider_point', label: '11Pay 포인트', type: 'divider' },
    { name: 'llpayPointEnabled', label: '11Pay 포인트 적립', type: 'checkbox' },
    { name: 'llpayPointType', label: '적립 방식', type: 'select', options: [
      { value: '02', label: '정액 (원)' }, { value: '01', label: '정률 (%)' },
    ]},
    { name: 'llpayPointValue', label: '적립 값 (원 또는 %)', type: 'number', placeholder: '100' },
  ]},
  { key: 'toss', label: '토스', authField: 'apiKey', guideUrl: 'https://shopping-docs.toss.im/dev', fields: [
    { name: 'businessName', label: '사업자명', type: 'text', placeholder: '상호명 입력' },
    { name: 'storeId', label: '스토어 ID', type: 'text' },
    { name: 'apiKey', label: 'API Key', type: 'text' },
    { name: 'apiSecret', label: 'API Secret', type: 'password' },
    { name: 'asPhone', label: 'A/S 전화번호', type: 'text', placeholder: '010-1234-5678' },
    { name: 'asMessage', label: 'A/S 안내 문구', type: 'text', placeholder: '상세페이지 참조' },
    { name: 'discountRate', label: '즉시할인율(%)', type: 'number', placeholder: '0 (미설정)' },
    { name: 'returnFee', label: '반품배송비(편도)', type: 'number', placeholder: '3000' },
    { name: 'exchangeFee', label: '교환배송비(왕복)', type: 'number', placeholder: '6000' },
    { name: 'jejuFee', label: '제주/도서산간 추가비', type: 'number', placeholder: '3000' },
    { name: 'stockQuantity', label: '재고수량', type: 'number', placeholder: '999 (기본값)' },
    { name: 'maxCount', label: '최대 등록 갯수', type: 'number', placeholder: '∞ 무제한' },
    { name: '_divider_purchase', label: '구매/리뷰 혜택 조건', type: 'divider' },
    { name: 'multiPurchaseDiscount', label: '복수구매할인', type: 'select', options: [
      { value: '', label: '설정안함' }, { value: 'true', label: '설정함' },
    ]},
    { name: 'multiPurchaseQty', label: '복수구매 수량 (N개 이상)', type: 'number', placeholder: '2' },
    { name: 'multiPurchaseRate', label: '복수구매 할인율 (%)', type: 'number', placeholder: '1' },
    { name: '_divider_point', label: '포인트', type: 'divider' },
    { name: 'purchasePointEnabled', label: '상품 구매 시 지급', type: 'checkbox' },
    { name: 'purchasePointRate', label: '구매 적립률 (%)', type: 'number', placeholder: '1' },
    { name: '_divider_review', label: '상품리뷰 작성시 지급', type: 'divider' },
    { name: 'reviewPointEnabled', label: '리뷰 포인트 지급', type: 'checkbox' },
    { name: 'reviewTextPoint', label: '텍스트 리뷰 작성', type: 'number', placeholder: '원' },
    { name: 'reviewPhotoPoint', label: '포토/동영상 리뷰 작성', type: 'number', placeholder: '원' },
    { name: 'reviewMonthTextPoint', label: '한달사용 텍스트 리뷰', type: 'number', placeholder: '원' },
    { name: 'reviewMonthPhotoPoint', label: '한달사용 포토/동영상 리뷰', type: 'number', placeholder: '원' },
  ]},
  { key: 'ssg', label: '신세계몰', authField: 'apiKey', guideUrl: 'https://opn-ssg.ssgadm.com', fields: [
    { name: 'businessName', label: '사업자명', type: 'text', placeholder: '상호명 입력' },
    { name: 'storeId', label: '스토어 ID', type: 'text' },
    { name: 'apiKey', label: 'API KEY', type: 'text' },
    { name: 'asPhone', label: 'A/S 전화번호', type: 'text', placeholder: '010-1234-5678' },
    { name: 'asMessage', label: 'A/S 안내 문구', type: 'text', placeholder: '상세페이지 참조' },
    { name: '_divider_margin', label: '가격 설정', type: 'divider' },
    { name: 'marginRate', label: '마진율(%)', type: 'number', placeholder: '15' },
    { name: 'feeRate', label: '수수료율(%)', type: 'number', placeholder: '20' },
    { name: '_divider_delivery_ssg', label: '배송 설정', type: 'divider' },
    { name: 'shippingCost', label: '배송비(원)', type: 'number', placeholder: '0' },
    { name: 'shppRqrmDcnt', label: '배송소요일', type: 'number', placeholder: '3' },
    { name: 'dayMaxQty', label: '1일 최대수량', type: 'number', placeholder: '5' },
    { name: 'onceMinQty', label: '1회 최소수량', type: 'number', placeholder: '1' },
    { name: 'onceMaxQty', label: '1회 최대수량', type: 'number', placeholder: '5' },
    { name: '_divider_shipping_code', label: '배송비/출고지 (SSG API 조회)', type: 'divider' },
    { name: 'whoutShppcstId', label: '출고배송비', type: 'ssg-shipping-select', placeholder: '버튼으로 불러오기' },
    { name: 'retShppcstId', label: '반품배송비', type: 'ssg-shipping-select', placeholder: '버튼으로 불러오기' },
    { name: 'addShppcstIdJeju', label: '제주 추가배송비', type: 'ssg-extra-select', placeholder: '버튼으로 불러오기' },
    { name: 'addShppcstIdIsland', label: '도서산간 추가배송비', type: 'ssg-extra-select', placeholder: '버튼으로 불러오기' },
    { name: 'whoutAddrId', label: '출고지', type: 'ssg-addr-select', placeholder: '버튼으로 불러오기' },
    { name: 'snbkAddrId', label: '반송지', type: 'ssg-addr-select', placeholder: '버튼으로 불러오기' },
    { name: 'maxCount', label: '최대 등록 갯수', type: 'number', placeholder: '∞ 무제한' },
  ]},
  { key: 'gsshop', label: 'GSSHOP', authField: 'apiKeyProd', guideUrl: 'https://partners.gsshop.com/api/apiMain', fields: [
    { name: 'businessName', label: '사업자명', type: 'text', placeholder: '상호명 입력' },
    { name: 'storeId', label: '스토어 ID', type: 'text' },
    { name: 'apiKeyDev', label: '개발 AES256 인증키', type: 'password' },
    { name: 'apiKeyProd', label: '운영 AES256 인증키', type: 'password' },
    { name: 'asPhone', label: 'A/S 전화번호', type: 'text', placeholder: '010-1234-5678' },
    { name: 'asMessage', label: 'A/S 안내 문구', type: 'text', placeholder: '상세페이지 참조' },
    { name: 'discountRate', label: '즉시할인율(%)', type: 'number', placeholder: '0 (미설정)' },
    { name: 'returnFee', label: '반품배송비(편도)', type: 'number', placeholder: '3000' },
    { name: 'exchangeFee', label: '교환배송비(왕복)', type: 'number', placeholder: '6000' },
    { name: 'jejuFee', label: '제주/도서산간 추가비', type: 'number', placeholder: '3000' },
    { name: 'stockQuantity', label: '재고수량', type: 'number', placeholder: '999 (기본값)' },
    { name: 'maxCount', label: '최대 등록 갯수', type: 'number', placeholder: '∞ 무제한' },
    { name: '_divider_purchase', label: '구매/리뷰 혜택 조건', type: 'divider' },
    { name: 'multiPurchaseDiscount', label: '복수구매할인', type: 'select', options: [
      { value: '', label: '설정안함' }, { value: 'true', label: '설정함' },
    ]},
    { name: 'multiPurchaseQty', label: '복수구매 수량 (N개 이상)', type: 'number', placeholder: '2' },
    { name: 'multiPurchaseRate', label: '복수구매 할인율 (%)', type: 'number', placeholder: '1' },
    { name: '_divider_point', label: '포인트', type: 'divider' },
    { name: 'purchasePointEnabled', label: '상품 구매 시 지급', type: 'checkbox' },
    { name: 'purchasePointRate', label: '구매 적립률 (%)', type: 'number', placeholder: '1' },
    { name: '_divider_review', label: '상품리뷰 작성시 지급', type: 'divider' },
    { name: 'reviewPointEnabled', label: '리뷰 포인트 지급', type: 'checkbox' },
    { name: 'reviewTextPoint', label: '텍스트 리뷰 작성', type: 'number', placeholder: '원' },
    { name: 'reviewPhotoPoint', label: '포토/동영상 리뷰 작성', type: 'number', placeholder: '원' },
    { name: 'reviewMonthTextPoint', label: '한달사용 텍스트 리뷰', type: 'number', placeholder: '원' },
    { name: 'reviewMonthPhotoPoint', label: '한달사용 포토/동영상 리뷰', type: 'number', placeholder: '원' },
  ]},
  { key: 'lottehome', label: '롯데홈쇼핑', authField: 'password', guideUrl: 'https://partner.lottehomeshopping.com', fields: [
    { name: 'businessName', label: '사업자명', type: 'text', placeholder: '상호명 입력' },
    { name: 'storeId', label: '로그인 ID', type: 'text', placeholder: '롯데홈쇼핑 로그인 ID' },
    { name: 'agncNo', label: '업체번호', type: 'text', placeholder: '예: 037800LT' },
    { name: 'password', label: '비밀번호', type: 'password' },
    { name: 'asPhone', label: 'A/S 전화번호', type: 'text', placeholder: '010-1234-5678' },
    { name: 'asMessage', label: 'A/S 안내 문구', type: 'text', placeholder: '상세페이지 참조' },
    { name: 'discountRate', label: '즉시할인율(%)', type: 'number', placeholder: '0 (미설정)' },
    { name: 'returnFee', label: '반품배송비(편도)', type: 'number', placeholder: '3000' },
    { name: 'exchangeFee', label: '교환배송비(왕복)', type: 'number', placeholder: '6000' },
    { name: 'jejuFee', label: '제주/도서산간 추가비', type: 'number', placeholder: '3000' },
    { name: 'stockQuantity', label: '재고수량', type: 'number', placeholder: '999 (기본값)' },
    { name: 'maxCount', label: '최대 등록 갯수', type: 'number', placeholder: '∞ 무제한' },
    { name: '_divider_lottehome_shipping', label: '배송정책/출고지 설정', type: 'divider' },
    { name: 'dlvPolcNo', label: '배송비정책', type: 'lottehome-policy-select' },
    { name: 'addDlvPolcNo', label: '추가배송비정책', type: 'lottehome-extra-policy-select' },
    { name: 'corpRlsPlSn', label: '출고지', type: 'lottehome-shipping-select' },
    { name: 'corpDlvpSn', label: '반품지', type: 'lottehome-return-select' },
  ]},
  { key: 'homeand', label: '홈앤쇼핑', authField: 'apiKey', guideUrl: 'https://partner.home-and.com', fields: [
    { name: 'businessName', label: '사업자명', type: 'text', placeholder: '상호명 입력' },
    { name: 'storeId', label: '스토어 ID', type: 'text' },
    { name: 'apiId', label: 'API ID', type: 'text' },
    { name: 'apiKey', label: 'API KEY', type: 'text' },
    { name: 'asPhone', label: 'A/S 전화번호', type: 'text', placeholder: '010-1234-5678' },
    { name: 'asMessage', label: 'A/S 안내 문구', type: 'text', placeholder: '상세페이지 참조' },
    { name: 'discountRate', label: '즉시할인율(%)', type: 'number', placeholder: '0 (미설정)' },
    { name: 'returnFee', label: '반품배송비(편도)', type: 'number', placeholder: '3000' },
    { name: 'exchangeFee', label: '교환배송비(왕복)', type: 'number', placeholder: '6000' },
    { name: 'jejuFee', label: '제주/도서산간 추가비', type: 'number', placeholder: '3000' },
    { name: 'stockQuantity', label: '재고수량', type: 'number', placeholder: '999 (기본값)' },
    { name: 'maxCount', label: '최대 등록 갯수', type: 'number', placeholder: '∞ 무제한' },
    { name: '_divider_purchase', label: '구매/리뷰 혜택 조건', type: 'divider' },
    { name: 'multiPurchaseDiscount', label: '복수구매할인', type: 'select', options: [
      { value: '', label: '설정안함' }, { value: 'true', label: '설정함' },
    ]},
    { name: 'multiPurchaseQty', label: '복수구매 수량 (N개 이상)', type: 'number', placeholder: '2' },
    { name: 'multiPurchaseRate', label: '복수구매 할인율 (%)', type: 'number', placeholder: '1' },
    { name: '_divider_point', label: '포인트', type: 'divider' },
    { name: 'purchasePointEnabled', label: '상품 구매 시 지급', type: 'checkbox' },
    { name: 'purchasePointRate', label: '구매 적립률 (%)', type: 'number', placeholder: '1' },
    { name: '_divider_review', label: '상품리뷰 작성시 지급', type: 'divider' },
    { name: 'reviewPointEnabled', label: '리뷰 포인트 지급', type: 'checkbox' },
    { name: 'reviewTextPoint', label: '텍스트 리뷰 작성', type: 'number', placeholder: '원' },
    { name: 'reviewPhotoPoint', label: '포토/동영상 리뷰 작성', type: 'number', placeholder: '원' },
    { name: 'reviewMonthTextPoint', label: '한달사용 텍스트 리뷰', type: 'number', placeholder: '원' },
    { name: 'reviewMonthPhotoPoint', label: '한달사용 포토/동영상 리뷰', type: 'number', placeholder: '원' },
  ]},
  { key: 'hmall', label: 'HMALL', authField: 'apiKey', guideUrl: 'https://partner.hmall.com', fields: [
    { name: 'businessName', label: '사업자명', type: 'text', placeholder: '상호명 입력' },
    { name: 'storeId', label: '스토어 ID', type: 'text' },
    { name: 'apiId', label: 'API ID', type: 'text' },
    { name: 'apiKey', label: 'API KEY', type: 'text' },
    { name: 'asPhone', label: 'A/S 전화번호', type: 'text', placeholder: '010-1234-5678' },
    { name: 'asMessage', label: 'A/S 안내 문구', type: 'text', placeholder: '상세페이지 참조' },
    { name: 'discountRate', label: '즉시할인율(%)', type: 'number', placeholder: '0 (미설정)' },
    { name: 'returnFee', label: '반품배송비(편도)', type: 'number', placeholder: '3000' },
    { name: 'exchangeFee', label: '교환배송비(왕복)', type: 'number', placeholder: '6000' },
    { name: 'jejuFee', label: '제주/도서산간 추가비', type: 'number', placeholder: '3000' },
    { name: 'stockQuantity', label: '재고수량', type: 'number', placeholder: '999 (기본값)' },
    { name: 'maxCount', label: '최대 등록 갯수', type: 'number', placeholder: '∞ 무제한' },
    { name: '_divider_purchase', label: '구매/리뷰 혜택 조건', type: 'divider' },
    { name: 'multiPurchaseDiscount', label: '복수구매할인', type: 'select', options: [
      { value: '', label: '설정안함' }, { value: 'true', label: '설정함' },
    ]},
    { name: 'multiPurchaseQty', label: '복수구매 수량 (N개 이상)', type: 'number', placeholder: '2' },
    { name: 'multiPurchaseRate', label: '복수구매 할인율 (%)', type: 'number', placeholder: '1' },
    { name: '_divider_point', label: '포인트', type: 'divider' },
    { name: 'purchasePointEnabled', label: '상품 구매 시 지급', type: 'checkbox' },
    { name: 'purchasePointRate', label: '구매 적립률 (%)', type: 'number', placeholder: '1' },
    { name: '_divider_review', label: '상품리뷰 작성시 지급', type: 'divider' },
    { name: 'reviewPointEnabled', label: '리뷰 포인트 지급', type: 'checkbox' },
    { name: 'reviewTextPoint', label: '텍스트 리뷰 작성', type: 'number', placeholder: '원' },
    { name: 'reviewPhotoPoint', label: '포토/동영상 리뷰 작성', type: 'number', placeholder: '원' },
    { name: 'reviewMonthTextPoint', label: '한달사용 텍스트 리뷰', type: 'number', placeholder: '원' },
    { name: 'reviewMonthPhotoPoint', label: '한달사용 포토/동영상 리뷰', type: 'number', placeholder: '원' },
  ]},
  { key: 'kream', label: 'KREAM', guideUrl: 'https://kream.co.kr/login', fields: [
    { name: 'businessName', label: '사업자명', type: 'text', placeholder: '상호명 입력' },
    { name: 'storeId', label: '스토어 ID', type: 'text' },
    { name: 'saleType', label: '판매유형', type: 'select', options: [
      { value: 'general', label: '일반판매' }, { value: 'storage', label: '보관판매' }, { value: 'grade95', label: '95점판매' },
    ]},
    { name: 'asPhone', label: 'A/S 전화번호', type: 'text', placeholder: '010-1234-5678' },
    { name: 'asMessage', label: 'A/S 안내 문구', type: 'text', placeholder: '상세페이지 참조' },
    { name: 'discountRate', label: '즉시할인율(%)', type: 'number', placeholder: '0 (미설정)' },
    { name: 'returnFee', label: '반품배송비(편도)', type: 'number', placeholder: '3000' },
    { name: 'exchangeFee', label: '교환배송비(왕복)', type: 'number', placeholder: '6000' },
    { name: 'jejuFee', label: '제주/도서산간 추가비', type: 'number', placeholder: '3000' },
    { name: 'stockQuantity', label: '재고수량', type: 'number', placeholder: '999 (기본값)' },
    { name: 'maxCount', label: '최대 등록 갯수', type: 'number', placeholder: '∞ 무제한' },
    { name: '_divider_purchase', label: '구매/리뷰 혜택 조건', type: 'divider' },
    { name: 'multiPurchaseDiscount', label: '복수구매할인', type: 'select', options: [
      { value: '', label: '설정안함' }, { value: 'true', label: '설정함' },
    ]},
    { name: 'multiPurchaseQty', label: '복수구매 수량 (N개 이상)', type: 'number', placeholder: '2' },
    { name: 'multiPurchaseRate', label: '복수구매 할인율 (%)', type: 'number', placeholder: '1' },
    { name: '_divider_point', label: '포인트', type: 'divider' },
    { name: 'purchasePointEnabled', label: '상품 구매 시 지급', type: 'checkbox' },
    { name: 'purchasePointRate', label: '구매 적립률 (%)', type: 'number', placeholder: '1' },
    { name: '_divider_review', label: '상품리뷰 작성시 지급', type: 'divider' },
    { name: 'reviewPointEnabled', label: '리뷰 포인트 지급', type: 'checkbox' },
    { name: 'reviewTextPoint', label: '텍스트 리뷰 작성', type: 'number', placeholder: '원' },
    { name: 'reviewPhotoPoint', label: '포토/동영상 리뷰 작성', type: 'number', placeholder: '원' },
    { name: 'reviewMonthTextPoint', label: '한달사용 텍스트 리뷰', type: 'number', placeholder: '원' },
    { name: 'reviewMonthPhotoPoint', label: '한달사용 포토/동영상 리뷰', type: 'number', placeholder: '원' },
  ]},
  { key: 'poison', label: '포이즌', authField: 'apiKey', guideUrl: 'https://www.poizon.com', fields: [
    { name: 'businessName', label: '사업자명', type: 'text', placeholder: '상호명 입력' },
    { name: 'storeId', label: '셀러 ID', type: 'text' },
    { name: 'apiKey', label: 'API Key / Token', type: 'text' },
    { name: 'apiSecret', label: 'API Secret', type: 'password' },
    { name: 'asPhone', label: 'A/S 전화번호', type: 'text', placeholder: '010-1234-5678' },
    { name: 'asMessage', label: 'A/S 안내 문구', type: 'text', placeholder: '상세페이지 참조' },
    { name: 'discountRate', label: '즉시할인율(%)', type: 'number', placeholder: '0 (미설정)' },
    { name: 'returnFee', label: '반품배송비(편도)', type: 'number', placeholder: '3000' },
    { name: 'exchangeFee', label: '교환배송비(왕복)', type: 'number', placeholder: '6000' },
    { name: 'jejuFee', label: '제주/도서산간 추가비', type: 'number', placeholder: '3000' },
    { name: 'stockQuantity', label: '재고수량', type: 'number', placeholder: '999 (기본값)' },
    { name: 'maxCount', label: '최대 등록 갯수', type: 'number', placeholder: '∞ 무제한' },
    { name: '_divider_purchase', label: '구매/리뷰 혜택 조건', type: 'divider' },
    { name: 'multiPurchaseDiscount', label: '복수구매할인', type: 'select', options: [
      { value: '', label: '설정안함' }, { value: 'true', label: '설정함' },
    ]},
    { name: 'multiPurchaseQty', label: '복수구매 수량 (N개 이상)', type: 'number', placeholder: '2' },
    { name: 'multiPurchaseRate', label: '복수구매 할인율 (%)', type: 'number', placeholder: '1' },
    { name: '_divider_point', label: '포인트', type: 'divider' },
    { name: 'purchasePointEnabled', label: '상품 구매 시 지급', type: 'checkbox' },
    { name: 'purchasePointRate', label: '구매 적립률 (%)', type: 'number', placeholder: '1' },
    { name: '_divider_review', label: '상품리뷰 작성시 지급', type: 'divider' },
    { name: 'reviewPointEnabled', label: '리뷰 포인트 지급', type: 'checkbox' },
    { name: 'reviewTextPoint', label: '텍스트 리뷰 작성', type: 'number', placeholder: '원' },
    { name: 'reviewPhotoPoint', label: '포토/동영상 리뷰 작성', type: 'number', placeholder: '원' },
    { name: 'reviewMonthTextPoint', label: '한달사용 텍스트 리뷰', type: 'number', placeholder: '원' },
    { name: 'reviewMonthPhotoPoint', label: '한달사용 포토/동영상 리뷰', type: 'number', placeholder: '원' },
  ]},
  { key: 'qoo10', label: 'Qoo10', authField: 'apiKey', guideUrl: 'https://qsm.qoo10.com/', fields: [
    { name: 'businessName', label: '사업자명', type: 'text', placeholder: '상호명 입력' },
    { name: 'storeId', label: 'Seller ID', type: 'text' },
    { name: 'apiKey', label: 'API Key', type: 'text' },
    { name: 'userKey', label: 'User Key', type: 'password' },
    { name: 'region', label: '지역', type: 'select', options: [
      { value: 'jp', label: 'Japan' }, { value: 'sg', label: 'Singapore' }, { value: 'global', label: 'Global' },
    ]},
    { name: 'asPhone', label: 'A/S 전화번호', type: 'text', placeholder: '010-1234-5678' },
    { name: 'asMessage', label: 'A/S 안내 문구', type: 'text', placeholder: '상세페이지 참조' },
    { name: 'discountRate', label: '즉시할인율(%)', type: 'number', placeholder: '0 (미설정)' },
    { name: 'returnFee', label: '반품배송비(편도)', type: 'number', placeholder: '3000' },
    { name: 'exchangeFee', label: '교환배송비(왕복)', type: 'number', placeholder: '6000' },
    { name: 'jejuFee', label: '제주/도서산간 추가비', type: 'number', placeholder: '3000' },
    { name: 'stockQuantity', label: '재고수량', type: 'number', placeholder: '999 (기본값)' },
    { name: 'maxCount', label: '최대 등록 갯수', type: 'number', placeholder: '∞ 무제한' },
    { name: '_divider_purchase', label: '구매/리뷰 혜택 조건', type: 'divider' },
    { name: 'multiPurchaseDiscount', label: '복수구매할인', type: 'select', options: [
      { value: '', label: '설정안함' }, { value: 'true', label: '설정함' },
    ]},
    { name: 'multiPurchaseQty', label: '복수구매 수량 (N개 이상)', type: 'number', placeholder: '2' },
    { name: 'multiPurchaseRate', label: '복수구매 할인율 (%)', type: 'number', placeholder: '1' },
    { name: '_divider_point', label: '포인트', type: 'divider' },
    { name: 'purchasePointEnabled', label: '상품 구매 시 지급', type: 'checkbox' },
    { name: 'purchasePointRate', label: '구매 적립률 (%)', type: 'number', placeholder: '1' },
    { name: '_divider_review', label: '상품리뷰 작성시 지급', type: 'divider' },
    { name: 'reviewPointEnabled', label: '리뷰 포인트 지급', type: 'checkbox' },
    { name: 'reviewTextPoint', label: '텍스트 리뷰 작성', type: 'number', placeholder: '원' },
    { name: 'reviewPhotoPoint', label: '포토/동영상 리뷰 작성', type: 'number', placeholder: '원' },
    { name: 'reviewMonthTextPoint', label: '한달사용 텍스트 리뷰', type: 'number', placeholder: '원' },
    { name: 'reviewMonthPhotoPoint', label: '한달사용 포토/동영상 리뷰', type: 'number', placeholder: '원' },
  ]},
  { key: 'rakuten', label: '라쿠텐', authField: 'apiKey', guideUrl: 'https://webservice.rakuten.co.jp/', fields: [
    { name: 'businessName', label: '사업자명', type: 'text', placeholder: '상호명 입력' },
    { name: 'storeId', label: '스토어 ID', type: 'text' },
    { name: 'apiKey', label: 'API Key / Service Secret', type: 'text' },
    { name: 'apiSecret', label: 'License Key', type: 'password' },
    { name: 'asPhone', label: 'A/S 전화번호', type: 'text', placeholder: '010-1234-5678' },
    { name: 'asMessage', label: 'A/S 안내 문구', type: 'text', placeholder: '상세페이지 참조' },
    { name: 'discountRate', label: '즉시할인율(%)', type: 'number', placeholder: '0 (미설정)' },
    { name: 'returnFee', label: '반품배송비(편도)', type: 'number', placeholder: '3000' },
    { name: 'exchangeFee', label: '교환배송비(왕복)', type: 'number', placeholder: '6000' },
    { name: 'jejuFee', label: '제주/도서산간 추가비', type: 'number', placeholder: '3000' },
    { name: 'stockQuantity', label: '재고수량', type: 'number', placeholder: '999 (기본값)' },
    { name: 'maxCount', label: '최대 등록 갯수', type: 'number', placeholder: '∞ 무제한' },
    { name: '_divider_purchase', label: '구매/리뷰 혜택 조건', type: 'divider' },
    { name: 'multiPurchaseDiscount', label: '복수구매할인', type: 'select', options: [
      { value: '', label: '설정안함' }, { value: 'true', label: '설정함' },
    ]},
    { name: 'multiPurchaseQty', label: '복수구매 수량 (N개 이상)', type: 'number', placeholder: '2' },
    { name: 'multiPurchaseRate', label: '복수구매 할인율 (%)', type: 'number', placeholder: '1' },
    { name: '_divider_point', label: '포인트', type: 'divider' },
    { name: 'purchasePointEnabled', label: '상품 구매 시 지급', type: 'checkbox' },
    { name: 'purchasePointRate', label: '구매 적립률 (%)', type: 'number', placeholder: '1' },
    { name: '_divider_review', label: '상품리뷰 작성시 지급', type: 'divider' },
    { name: 'reviewPointEnabled', label: '리뷰 포인트 지급', type: 'checkbox' },
    { name: 'reviewTextPoint', label: '텍스트 리뷰 작성', type: 'number', placeholder: '원' },
    { name: 'reviewPhotoPoint', label: '포토/동영상 리뷰 작성', type: 'number', placeholder: '원' },
    { name: 'reviewMonthTextPoint', label: '한달사용 텍스트 리뷰', type: 'number', placeholder: '원' },
    { name: 'reviewMonthPhotoPoint', label: '한달사용 포토/동영상 리뷰', type: 'number', placeholder: '원' },
  ]},
  { key: 'buyma', label: '바이마', authField: 'apiKey', guideUrl: 'https://www.buyma.com/buyer/', fields: [
    { name: 'businessName', label: '사업자명', type: 'text', placeholder: '상호명 입력' },
    { name: 'storeId', label: '셀러 ID', type: 'text' },
    { name: 'apiKey', label: 'API Key / Token', type: 'text' },
    { name: 'apiSecret', label: 'API Secret', type: 'password' },
    { name: 'asPhone', label: 'A/S 전화번호', type: 'text', placeholder: '010-1234-5678' },
    { name: 'asMessage', label: 'A/S 안내 문구', type: 'text', placeholder: '상세페이지 참조' },
    { name: 'discountRate', label: '즉시할인율(%)', type: 'number', placeholder: '0 (미설정)' },
    { name: 'returnFee', label: '반품배송비(편도)', type: 'number', placeholder: '3000' },
    { name: 'exchangeFee', label: '교환배송비(왕복)', type: 'number', placeholder: '6000' },
    { name: 'jejuFee', label: '제주/도서산간 추가비', type: 'number', placeholder: '3000' },
    { name: 'stockQuantity', label: '재고수량', type: 'number', placeholder: '999 (기본값)' },
    { name: 'maxCount', label: '최대 등록 갯수', type: 'number', placeholder: '∞ 무제한' },
    { name: '_divider_purchase', label: '구매/리뷰 혜택 조건', type: 'divider' },
    { name: 'multiPurchaseDiscount', label: '복수구매할인', type: 'select', options: [
      { value: '', label: '설정안함' }, { value: 'true', label: '설정함' },
    ]},
    { name: 'multiPurchaseQty', label: '복수구매 수량 (N개 이상)', type: 'number', placeholder: '2' },
    { name: 'multiPurchaseRate', label: '복수구매 할인율 (%)', type: 'number', placeholder: '1' },
    { name: '_divider_point', label: '포인트', type: 'divider' },
    { name: 'purchasePointEnabled', label: '상품 구매 시 지급', type: 'checkbox' },
    { name: 'purchasePointRate', label: '구매 적립률 (%)', type: 'number', placeholder: '1' },
    { name: '_divider_review', label: '상품리뷰 작성시 지급', type: 'divider' },
    { name: 'reviewPointEnabled', label: '리뷰 포인트 지급', type: 'checkbox' },
    { name: 'reviewTextPoint', label: '텍스트 리뷰 작성', type: 'number', placeholder: '원' },
    { name: 'reviewPhotoPoint', label: '포토/동영상 리뷰 작성', type: 'number', placeholder: '원' },
    { name: 'reviewMonthTextPoint', label: '한달사용 텍스트 리뷰', type: 'number', placeholder: '원' },
    { name: 'reviewMonthPhotoPoint', label: '한달사용 포토/동영상 리뷰', type: 'number', placeholder: '원' },
  ]},
  { key: 'lazada', label: 'Lazada', authField: 'accessToken', guideUrl: 'https://open.lazada.com/', fields: [
    { name: 'businessName', label: '사업자명', type: 'text', placeholder: '상호명 입력' },
    { name: 'storeId', label: 'Seller ID', type: 'text' },
    { name: 'appKey', label: 'App Key', type: 'text' },
    { name: 'appSecret', label: 'App Secret', type: 'password' },
    { name: 'accessToken', label: 'Access Token', type: 'password' },
    { name: 'region', label: '지역', type: 'select', options: [
      { value: 'sg', label: 'Singapore' }, { value: 'my', label: 'Malaysia' }, { value: 'th', label: 'Thailand' },
      { value: 'ph', label: 'Philippines' }, { value: 'id', label: 'Indonesia' }, { value: 'vn', label: 'Vietnam' },
    ]},
    { name: 'asPhone', label: 'A/S 전화번호', type: 'text', placeholder: '010-1234-5678' },
    { name: 'asMessage', label: 'A/S 안내 문구', type: 'text', placeholder: '상세페이지 참조' },
    { name: 'discountRate', label: '즉시할인율(%)', type: 'number', placeholder: '0 (미설정)' },
    { name: 'returnFee', label: '반품배송비(편도)', type: 'number', placeholder: '3000' },
    { name: 'exchangeFee', label: '교환배송비(왕복)', type: 'number', placeholder: '6000' },
    { name: 'jejuFee', label: '제주/도서산간 추가비', type: 'number', placeholder: '3000' },
    { name: 'stockQuantity', label: '재고수량', type: 'number', placeholder: '999 (기본값)' },
    { name: 'maxCount', label: '최대 등록 갯수', type: 'number', placeholder: '∞ 무제한' },
    { name: '_divider_purchase', label: '구매/리뷰 혜택 조건', type: 'divider' },
    { name: 'multiPurchaseDiscount', label: '복수구매할인', type: 'select', options: [
      { value: '', label: '설정안함' }, { value: 'true', label: '설정함' },
    ]},
    { name: 'multiPurchaseQty', label: '복수구매 수량 (N개 이상)', type: 'number', placeholder: '2' },
    { name: 'multiPurchaseRate', label: '복수구매 할인율 (%)', type: 'number', placeholder: '1' },
    { name: '_divider_point', label: '포인트', type: 'divider' },
    { name: 'purchasePointEnabled', label: '상품 구매 시 지급', type: 'checkbox' },
    { name: 'purchasePointRate', label: '구매 적립률 (%)', type: 'number', placeholder: '1' },
    { name: '_divider_review', label: '상품리뷰 작성시 지급', type: 'divider' },
    { name: 'reviewPointEnabled', label: '리뷰 포인트 지급', type: 'checkbox' },
    { name: 'reviewTextPoint', label: '텍스트 리뷰 작성', type: 'number', placeholder: '원' },
    { name: 'reviewPhotoPoint', label: '포토/동영상 리뷰 작성', type: 'number', placeholder: '원' },
    { name: 'reviewMonthTextPoint', label: '한달사용 텍스트 리뷰', type: 'number', placeholder: '원' },
    { name: 'reviewMonthPhotoPoint', label: '한달사용 포토/동영상 리뷰', type: 'number', placeholder: '원' },
  ]},
  { key: 'shopify', label: 'Shopify', authField: 'accessToken', guideUrl: 'https://shopify.dev/docs/api', fields: [
    { name: 'businessName', label: '스토어명', type: 'text', placeholder: '상호명 입력' },
    { name: 'storeId', label: '스토어 도메인', type: 'text', placeholder: 'mystore.myshopify.com' },
    { name: 'accessToken', label: 'Admin API Access Token', type: 'password' },
    { name: 'asPhone', label: 'A/S 전화번호', type: 'text', placeholder: '010-1234-5678' },
    { name: 'asMessage', label: 'A/S 안내 문구', type: 'text', placeholder: '상세페이지 참조' },
    { name: 'discountRate', label: '즉시할인율(%)', type: 'number', placeholder: '0 (미설정)' },
    { name: 'returnFee', label: '반품배송비(편도)', type: 'number', placeholder: '3000' },
    { name: 'exchangeFee', label: '교환배송비(왕복)', type: 'number', placeholder: '6000' },
    { name: 'jejuFee', label: '제주/도서산간 추가비', type: 'number', placeholder: '3000' },
    { name: 'stockQuantity', label: '재고수량', type: 'number', placeholder: '999 (기본값)' },
    { name: 'maxCount', label: '최대 등록 갯수', type: 'number', placeholder: '∞ 무제한' },
    { name: '_divider_purchase', label: '구매/리뷰 혜택 조건', type: 'divider' },
    { name: 'multiPurchaseDiscount', label: '복수구매할인', type: 'select', options: [
      { value: '', label: '설정안함' }, { value: 'true', label: '설정함' },
    ]},
    { name: 'multiPurchaseQty', label: '복수구매 수량 (N개 이상)', type: 'number', placeholder: '2' },
    { name: 'multiPurchaseRate', label: '복수구매 할인율 (%)', type: 'number', placeholder: '1' },
    { name: '_divider_point', label: '포인트', type: 'divider' },
    { name: 'purchasePointEnabled', label: '상품 구매 시 지급', type: 'checkbox' },
    { name: 'purchasePointRate', label: '구매 적립률 (%)', type: 'number', placeholder: '1' },
    { name: '_divider_review', label: '상품리뷰 작성시 지급', type: 'divider' },
    { name: 'reviewPointEnabled', label: '리뷰 포인트 지급', type: 'checkbox' },
    { name: 'reviewTextPoint', label: '텍스트 리뷰 작성', type: 'number', placeholder: '원' },
    { name: 'reviewPhotoPoint', label: '포토/동영상 리뷰 작성', type: 'number', placeholder: '원' },
    { name: 'reviewMonthTextPoint', label: '한달사용 텍스트 리뷰', type: 'number', placeholder: '원' },
    { name: 'reviewMonthPhotoPoint', label: '한달사용 포토/동영상 리뷰', type: 'number', placeholder: '원' },
  ]},
  { key: 'shopee', label: 'Shopee', authField: 'accessToken', guideUrl: 'https://open.shopee.com/', fields: [
    { name: 'businessName', label: '사업자명', type: 'text', placeholder: '상호명 입력' },
    { name: 'storeId', label: 'Shop ID', type: 'text' },
    { name: 'partnerId', label: 'Partner ID', type: 'text' },
    { name: 'partnerKey', label: 'Partner Key', type: 'password' },
    { name: 'accessToken', label: 'Access Token', type: 'password' },
    { name: 'region', label: '지역', type: 'select', options: [
      { value: 'sg', label: 'Singapore' }, { value: 'my', label: 'Malaysia' }, { value: 'th', label: 'Thailand' },
      { value: 'ph', label: 'Philippines' }, { value: 'id', label: 'Indonesia' }, { value: 'vn', label: 'Vietnam' },
      { value: 'tw', label: 'Taiwan' }, { value: 'br', label: 'Brazil' },
    ]},
    { name: 'asPhone', label: 'A/S 전화번호', type: 'text', placeholder: '010-1234-5678' },
    { name: 'asMessage', label: 'A/S 안내 문구', type: 'text', placeholder: '상세페이지 참조' },
    { name: 'discountRate', label: '즉시할인율(%)', type: 'number', placeholder: '0 (미설정)' },
    { name: 'returnFee', label: '반품배송비(편도)', type: 'number', placeholder: '3000' },
    { name: 'exchangeFee', label: '교환배송비(왕복)', type: 'number', placeholder: '6000' },
    { name: 'jejuFee', label: '제주/도서산간 추가비', type: 'number', placeholder: '3000' },
    { name: 'stockQuantity', label: '재고수량', type: 'number', placeholder: '999 (기본값)' },
    { name: 'maxCount', label: '최대 등록 갯수', type: 'number', placeholder: '∞ 무제한' },
    { name: '_divider_purchase', label: '구매/리뷰 혜택 조건', type: 'divider' },
    { name: 'multiPurchaseDiscount', label: '복수구매할인', type: 'select', options: [
      { value: '', label: '설정안함' }, { value: 'true', label: '설정함' },
    ]},
    { name: 'multiPurchaseQty', label: '복수구매 수량 (N개 이상)', type: 'number', placeholder: '2' },
    { name: 'multiPurchaseRate', label: '복수구매 할인율 (%)', type: 'number', placeholder: '1' },
    { name: '_divider_point', label: '포인트', type: 'divider' },
    { name: 'purchasePointEnabled', label: '상품 구매 시 지급', type: 'checkbox' },
    { name: 'purchasePointRate', label: '구매 적립률 (%)', type: 'number', placeholder: '1' },
    { name: '_divider_review', label: '상품리뷰 작성시 지급', type: 'divider' },
    { name: 'reviewPointEnabled', label: '리뷰 포인트 지급', type: 'checkbox' },
    { name: 'reviewTextPoint', label: '텍스트 리뷰 작성', type: 'number', placeholder: '원' },
    { name: 'reviewPhotoPoint', label: '포토/동영상 리뷰 작성', type: 'number', placeholder: '원' },
    { name: 'reviewMonthTextPoint', label: '한달사용 텍스트 리뷰', type: 'number', placeholder: '원' },
    { name: 'reviewMonthPhotoPoint', label: '한달사용 포토/동영상 리뷰', type: 'number', placeholder: '원' },
  ]},
  { key: 'zoom', label: 'Zum(줌)', authField: 'apiKey', guideUrl: 'https://shopping.zum.com/seller', fields: [
    { name: 'businessName', label: '사업자명', type: 'text', placeholder: '상호명 입력' },
    { name: 'storeId', label: '스토어 ID', type: 'text' },
    { name: 'apiKey', label: 'API Key', type: 'text' },
    { name: 'apiSecret', label: 'API Secret', type: 'password' },
    { name: 'asPhone', label: 'A/S 전화번호', type: 'text', placeholder: '010-1234-5678' },
    { name: 'asMessage', label: 'A/S 안내 문구', type: 'text', placeholder: '상세페이지 참조' },
    { name: 'discountRate', label: '즉시할인율(%)', type: 'number', placeholder: '0 (미설정)' },
    { name: 'returnFee', label: '반품배송비(편도)', type: 'number', placeholder: '3000' },
    { name: 'exchangeFee', label: '교환배송비(왕복)', type: 'number', placeholder: '6000' },
    { name: 'jejuFee', label: '제주/도서산간 추가비', type: 'number', placeholder: '3000' },
    { name: 'stockQuantity', label: '재고수량', type: 'number', placeholder: '999 (기본값)' },
    { name: 'maxCount', label: '최대 등록 갯수', type: 'number', placeholder: '∞ 무제한' },
    { name: '_divider_purchase', label: '구매/리뷰 혜택 조건', type: 'divider' },
    { name: 'multiPurchaseDiscount', label: '복수구매할인', type: 'select', options: [
      { value: '', label: '설정안함' }, { value: 'true', label: '설정함' },
    ]},
    { name: 'multiPurchaseQty', label: '복수구매 수량 (N개 이상)', type: 'number', placeholder: '2' },
    { name: 'multiPurchaseRate', label: '복수구매 할인율 (%)', type: 'number', placeholder: '1' },
    { name: '_divider_point', label: '포인트', type: 'divider' },
    { name: 'purchasePointEnabled', label: '상품 구매 시 지급', type: 'checkbox' },
    { name: 'purchasePointRate', label: '구매 적립률 (%)', type: 'number', placeholder: '1' },
    { name: '_divider_review', label: '상품리뷰 작성시 지급', type: 'divider' },
    { name: 'reviewPointEnabled', label: '리뷰 포인트 지급', type: 'checkbox' },
    { name: 'reviewTextPoint', label: '텍스트 리뷰 작성', type: 'number', placeholder: '원' },
    { name: 'reviewPhotoPoint', label: '포토/동영상 리뷰 작성', type: 'number', placeholder: '원' },
    { name: 'reviewMonthTextPoint', label: '한달사용 텍스트 리뷰', type: 'number', placeholder: '원' },
    { name: 'reviewMonthPhotoPoint', label: '한달사용 포토/동영상 리뷰', type: 'number', placeholder: '원' },
  ]},
  { key: 'ebay', label: 'eBay', authField: 'oauthToken', guideUrl: 'https://developer.ebay.com/', fields: [
    { name: 'businessName', label: '사업자명', type: 'text', placeholder: '상호명 입력' },
    { name: 'storeId', label: 'eBay Seller ID', type: 'text' },
    { name: 'clientId', label: 'App ID (Client ID)', type: 'text' },
    { name: 'clientSecret', label: 'Cert ID (Client Secret)', type: 'password' },
    { name: 'oauthToken', label: 'OAuth Refresh Token', type: 'password' },
    { name: 'siteId', label: 'Site ID', type: 'select', options: [
      { value: '0', label: 'US (0)' }, { value: '3', label: 'UK (3)' }, { value: '77', label: 'DE (77)' }, { value: '15', label: 'AU (15)' },
    ]},
    { name: 'asPhone', label: 'A/S 전화번호', type: 'text', placeholder: '010-1234-5678' },
    { name: 'asMessage', label: 'A/S 안내 문구', type: 'text', placeholder: '상세페이지 참조' },
    { name: 'discountRate', label: '즉시할인율(%)', type: 'number', placeholder: '0 (미설정)' },
    { name: 'returnFee', label: '반품배송비(편도)', type: 'number', placeholder: '3000' },
    { name: 'exchangeFee', label: '교환배송비(왕복)', type: 'number', placeholder: '6000' },
    { name: 'jejuFee', label: '제주/도서산간 추가비', type: 'number', placeholder: '3000' },
    { name: 'stockQuantity', label: '재고수량', type: 'number', placeholder: '999 (기본값)' },
    { name: 'maxCount', label: '최대 등록 갯수', type: 'number', placeholder: '∞ 무제한' },
    { name: '_divider_purchase', label: '구매/리뷰 혜택 조건', type: 'divider' },
    { name: 'multiPurchaseDiscount', label: '복수구매할인', type: 'select', options: [
      { value: '', label: '설정안함' }, { value: 'true', label: '설정함' },
    ]},
    { name: 'multiPurchaseQty', label: '복수구매 수량 (N개 이상)', type: 'number', placeholder: '2' },
    { name: 'multiPurchaseRate', label: '복수구매 할인율 (%)', type: 'number', placeholder: '1' },
    { name: '_divider_point', label: '포인트', type: 'divider' },
    { name: 'purchasePointEnabled', label: '상품 구매 시 지급', type: 'checkbox' },
    { name: 'purchasePointRate', label: '구매 적립률 (%)', type: 'number', placeholder: '1' },
    { name: '_divider_review', label: '상품리뷰 작성시 지급', type: 'divider' },
    { name: 'reviewPointEnabled', label: '리뷰 포인트 지급', type: 'checkbox' },
    { name: 'reviewTextPoint', label: '텍스트 리뷰 작성', type: 'number', placeholder: '원' },
    { name: 'reviewPhotoPoint', label: '포토/동영상 리뷰 작성', type: 'number', placeholder: '원' },
    { name: 'reviewMonthTextPoint', label: '한달사용 텍스트 리뷰', type: 'number', placeholder: '원' },
    { name: 'reviewMonthPhotoPoint', label: '한달사용 포토/동영상 리뷰', type: 'number', placeholder: '원' },
  ]},
  { key: 'amazon', label: '아마존', authField: 'accessToken', guideUrl: 'https://developer-docs.amazon.com/sp-api/', fields: [
    { name: 'businessName', label: '사업자명', type: 'text', placeholder: '상호명 입력' },
    { name: 'storeId', label: 'Seller ID', type: 'text' },
    { name: 'accessToken', label: 'Refresh Token', type: 'password' },
    { name: 'clientId', label: 'Client ID (LWA)', type: 'text' },
    { name: 'clientSecret', label: 'Client Secret (LWA)', type: 'password' },
    { name: 'asPhone', label: 'A/S 전화번호', type: 'text', placeholder: '010-1234-5678' },
    { name: 'asMessage', label: 'A/S 안내 문구', type: 'text', placeholder: '상세페이지 참조' },
    { name: 'discountRate', label: '즉시할인율(%)', type: 'number', placeholder: '0 (미설정)' },
    { name: 'returnFee', label: '반품배송비(편도)', type: 'number', placeholder: '3000' },
    { name: 'exchangeFee', label: '교환배송비(왕복)', type: 'number', placeholder: '6000' },
    { name: 'jejuFee', label: '제주/도서산간 추가비', type: 'number', placeholder: '3000' },
    { name: 'stockQuantity', label: '재고수량', type: 'number', placeholder: '999 (기본값)' },
    { name: 'maxCount', label: '최대 등록 갯수', type: 'number', placeholder: '∞ 무제한' },
    { name: '_divider_purchase', label: '구매/리뷰 혜택 조건', type: 'divider' },
    { name: 'multiPurchaseDiscount', label: '복수구매할인', type: 'select', options: [
      { value: '', label: '설정안함' }, { value: 'true', label: '설정함' },
    ]},
    { name: 'multiPurchaseQty', label: '복수구매 수량 (N개 이상)', type: 'number', placeholder: '2' },
    { name: 'multiPurchaseRate', label: '복수구매 할인율 (%)', type: 'number', placeholder: '1' },
    { name: '_divider_point', label: '포인트', type: 'divider' },
    { name: 'purchasePointEnabled', label: '상품 구매 시 지급', type: 'checkbox' },
    { name: 'purchasePointRate', label: '구매 적립률 (%)', type: 'number', placeholder: '1' },
    { name: '_divider_review', label: '상품리뷰 작성시 지급', type: 'divider' },
    { name: 'reviewPointEnabled', label: '리뷰 포인트 지급', type: 'checkbox' },
    { name: 'reviewTextPoint', label: '텍스트 리뷰 작성', type: 'number', placeholder: '원' },
    { name: 'reviewPhotoPoint', label: '포토/동영상 리뷰 작성', type: 'number', placeholder: '원' },
    { name: 'reviewMonthTextPoint', label: '한달사용 텍스트 리뷰', type: 'number', placeholder: '원' },
    { name: 'reviewMonthPhotoPoint', label: '한달사용 포토/동영상 리뷰', type: 'number', placeholder: '원' },
  ]},
  { key: 'playauto', label: '플레이오토', authField: 'apiKey', guideUrl: 'https://www.plto.com', fields: [
    { name: 'businessName', label: '사업자명', type: 'text', placeholder: '상호명 입력' },
    { name: 'storeId', label: '판매자 ID', type: 'text' },
    { name: 'password', label: 'PASSWORD', type: 'password' },
    { name: 'apiKey', label: 'API Key', type: 'text' },
    { name: 'apiSecret', label: '솔루션코드', type: 'password' },
    { name: 'stockQuantity', label: '재고수량', type: 'number', placeholder: '99 (기본값)' },
    { name: 'maxCount', label: '최대 등록 갯수', type: 'number', placeholder: '∞ 무제한' },
    { name: '_divider_alias', label: '마켓번호 별칭 (주문페이지 표시용)', type: 'divider' },
    { name: 'alias1', label: '계정 1', type: 'alias', placeholder: '037800LT' },
    { name: 'alias2', label: '계정 2', type: 'alias', placeholder: '마켓번호' },
    { name: 'alias3', label: '계정 3', type: 'alias', placeholder: '마켓번호' },
    { name: 'alias4', label: '계정 4', type: 'alias', placeholder: '마켓번호' },
    { name: 'alias5', label: '계정 5', type: 'alias', placeholder: '마켓번호' },
  ]},
  { key: 'cafe24', label: '카페24', authField: 'accessToken', guideUrl: 'https://developers.cafe24.com', fields: [
    { name: 'businessName', label: '사업자명', type: 'text', placeholder: '상호명 입력' },
    { name: 'storeId', label: '쇼핑몰 ID (mall_id)', type: 'text' },
    { name: 'clientId', label: 'Client ID', type: 'text' },
    { name: 'clientSecret', label: 'Client Secret', type: 'password' },
    { name: 'accessToken', label: 'Access Token', type: 'password' },
    { name: 'asPhone', label: 'A/S 전화번호', type: 'text', placeholder: '010-1234-5678' },
    { name: 'asMessage', label: 'A/S 안내 문구', type: 'text', placeholder: '상세페이지 참조' },
    { name: 'discountRate', label: '즉시할인율(%)', type: 'number', placeholder: '0 (미설정)' },
    { name: 'returnFee', label: '반품배송비(편도)', type: 'number', placeholder: '3000' },
    { name: 'exchangeFee', label: '교환배송비(왕복)', type: 'number', placeholder: '6000' },
    { name: 'jejuFee', label: '제주/도서산간 추가비', type: 'number', placeholder: '3000' },
    { name: 'stockQuantity', label: '재고수량', type: 'number', placeholder: '999 (기본값)' },
    { name: 'maxCount', label: '최대 등록 갯수', type: 'number', placeholder: '∞ 무제한' },
    { name: '_divider_purchase', label: '구매/리뷰 혜택 조건', type: 'divider' },
    { name: 'multiPurchaseDiscount', label: '복수구매할인', type: 'select', options: [
      { value: '', label: '설정안함' }, { value: 'true', label: '설정함' },
    ]},
    { name: 'multiPurchaseQty', label: '복수구매 수량 (N개 이상)', type: 'number', placeholder: '2' },
    { name: 'multiPurchaseRate', label: '복수구매 할인율 (%)', type: 'number', placeholder: '1' },
    { name: '_divider_point', label: '포인트', type: 'divider' },
    { name: 'purchasePointEnabled', label: '상품 구매 시 지급', type: 'checkbox' },
    { name: 'purchasePointRate', label: '구매 적립률 (%)', type: 'number', placeholder: '1' },
    { name: '_divider_review', label: '상품리뷰 작성시 지급', type: 'divider' },
    { name: 'reviewPointEnabled', label: '리뷰 포인트 지급', type: 'checkbox' },
    { name: 'reviewTextPoint', label: '텍스트 리뷰 작성', type: 'number', placeholder: '원' },
    { name: 'reviewPhotoPoint', label: '포토/동영상 리뷰 작성', type: 'number', placeholder: '원' },
    { name: 'reviewMonthTextPoint', label: '한달사용 텍스트 리뷰', type: 'number', placeholder: '원' },
    { name: 'reviewMonthPhotoPoint', label: '한달사용 포토/동영상 리뷰', type: 'number', placeholder: '원' },
  ]},
]

// select 필드에 대해 DB에 값이 없을 때 주입할 "안전한 기본값"
// ※ 이곳에 등록된 필드만 초기값이 자동 주입된다.
// ※ 의도치 않은 정책 변경(예: dispatchDays) 방지를 위해 화이트리스트 방식으로 관리.
export const SAFE_SELECT_DEFAULTS: Record<string, string> = {
  bundleDelivery: 'N',   // 롯데ON 합배송 — 보수적 기본값("불가능")
  env: 'prod',           // 롯데홈쇼핑 API 환경 — 기본값 운영
}
